[project]
name = "how-to-load-toml-with-pydantic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic-settings>=2.7.1",
    "pyyaml>=6.0.2",
]
